"""create students, attendance, grades, teacher_notes

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-12 20:34:46.162347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.types


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_teacher_id'), 'students', ['teacher_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('student_id', app.models.types.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('present', 'absent', 'late')", name='ck_attendance_status'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_attendance_student_date')
    )
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('student_id', app.models.types.GUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('assessment_name', sa.String(length=200), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_grades_max_score_positive'),
    sa.CheckConstraint('score <= max_score', name='ck_grades_score_le_max'),
    sa.CheckConstraint('score >= 0', name='ck_grades_score_non_negative'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_table('teacher_notes',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('student_id', app.models.types.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.types.GUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_notes_student_id'), 'teacher_notes', ['student_id'], unique=False)
    op.create_index(op.f('ix_teacher_notes_teacher_id'), 'teacher_notes', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_notes_teacher_id'), table_name='teacher_notes')
    op.drop_index(op.f('ix_teacher_notes_student_id'), table_name='teacher_notes')
    op.drop_table('teacher_notes')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_students_teacher_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
